### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by aairey**

### CODE REVIEW

**Comment by aairey** [comment]
Also the Maven plugin is no longer available but we can build from source.

**Comment by Download** [comment]
Actually, the Maven plugin is not yet available. I was preparing to publish this to Maven Central but life intervened... But I have to say that it's great people are already trying to get it to work. That's really encouraging! So I will spend some time this weekend trying to get this published on Maven Central and making sure the example works as advertised.

**Comment by Download** [comment]
Thanks for your PR!

It is my custom to invite people that offer PRs that get merged to become collaborators. Because people that submit PRs are the people that make the difference imho. So thank you again! Here's your invite:

https://github.com/Download/undertow-cors-filter/invitations

**Comment by Download** [comment]
Included in [release 0.2.0](https://github.com/Download/undertow-cors-filter/releases/tag/0.2.0)

I published to Maven Central, but it may still take some time before it is available there. Especially the first release always takes some time.

Edit: well that happened pretty fast. Release is available on Maven Central now.

**Comment by Download** [comment]
Please ignore all release before 0.4.0. There were some issues in it still.
0.4.0 I've labeled Release Candidate 1. It's on Maven Central. I'd be interested in feedback from your end. Is this suitable to promote to 1.0.0?

**Comment by aairey** [comment]
Thanks!

Unfortunately for this project we have found a solution to the problem we were troubleshooting relating CORS and will not be able to test this for some time ...

**Pull request merged**
